export { default as Works } from './works/Works'
export { default as Footer } from './footer/Footer'
export { default as Hero } from './hero/Hero'
export { default as Services } from './services/Services'
export { default as Resume } from './Resume/Resume'