export { default as Article } from './article/Article'
export { default as Brand } from './brand/Brand'
export { default as Contact } from './contact/Contact'
export { default as Service } from './service/Service'
export { default as Navbar } from './navbar/Navbar'