export { default as ContactForm } from './contactForm/ContactForm'
export { default as SocialMedia } from './socialmedia/SocialMedia'
export { default as Contact } from './contact/Contact'
export { default as Service } from './service/Service'
export { default as Navbar } from './navbar/Navbar'