export { default as ContactForm } from './contactForm/ContactForm'
export { default as SocialMedia } from './socialmedia/SocialMedia'
export { default as Contact } from './contact/Contact'
export { default as Service } from './service/Service'
export { default as Navbar } from './navbar/Navbar'
export { default as Work } from './work/Work'
export { default as Education } from './education/Education'
export { default as WorkExperience} from './workExperience/WorkExperience'
export { default as TimelineBlock } from './timelineBlock/TimelineBlock'